const REPO = 'kushagra0328/tilak-ventures-ir';
const COOKIE = 'tv_cms_session';

function json(data, status=200, extra={}) { return new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json; charset=utf-8', ...extra}}); }
async function hmac(secret, text) { const key=await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), {name:'HMAC',hash:'SHA-256'}, false, ['sign']); const sig=await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(text)); return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
async function sessionToken(env) { const exp=Date.now()+8*60*60*1000; return `${exp}.${await hmac(env.SESSION_SECRET,String(exp))}`; }
async function validSession(req,env) { const c=req.headers.get('Cookie')||''; const m=c.match(new RegExp(`${COOKIE}=([^;]+)`)); if(!m)return false; const [exp,sig]=m[1].split('.'); if(!exp||Number(exp)<Date.now())return false; return sig===await hmac(env.SESSION_SECRET,exp); }
function safeName(s){return s.replace(/[^A-Za-z0-9._-]/g,'-');}
function resultName(fy,q){const [a,b]=fy.split('-').map(Number); return ({Q1:`Jun-${String(a).slice(-2)}`,Q2:`Sep-${String(a).slice(-2)}`,Q3:`Dec-${String(a).slice(-2)}`,Q4:`Mar-${String(b).slice(-2)}`})[q]+'.pdf';}
async function gh(path,env,method='GET',body){ const url=`https://api.github.com/repos/${REPO}/contents/${path}`; const r=await fetch(url,{method,headers:{Authorization:`Bearer ${env.GITHUB_TOKEN}`,'User-Agent':'tilak-ventures-cms','Accept':'application/vnd.github+json','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}); return r; }
export default { async fetch(req,env,ctx){ const u=new URL(req.url); if(req.method==='POST'&&u.pathname==='/api/login'){ const b=await req.json(); if(!b.password||b.password!==env.ADMIN_PASSWORD)return json({error:'Invalid password'},401); const t=await sessionToken(env); return json({ok:true},{headers:{'Set-Cookie':`${COOKIE}=${t}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`}}); }
 if(req.method==='POST'&&u.pathname==='/api/logout'){return json({ok:true},{headers:{'Set-Cookie':`${COOKIE}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict`}});}
 if(u.pathname.startsWith('/api/')){ if(!(await validSession(req,env)))return json({error:'Unauthorised'},401); if(req.method==='POST'&&u.pathname==='/api/upload'){ const form=await req.formData(); const type=String(form.get('type')||''); const fy=String(form.get('fy')||''); const quarter=String(form.get('quarter')||''); const title=String(form.get('title')||''); const file=form.get('file'); if(!(file instanceof File))return json({error:'PDF required'},400); if(file.type!=='application/pdf')return json({error:'Only PDF files are allowed'},400); if(file.size>20*1024*1024)return json({error:'Maximum file size is 20 MB'},400); let name=''; let folder=''; if(type==='results'){ if(!/^\d{4}-\d{2}$/.test(fy)||!/^Q[1-4]$/.test(quarter))return json({error:'Select financial year and quarter'},400); name=resultName(fy,quarter); folder='results'; } else if(type==='annual-report'){ if(!/^\d{4}-\d{2}$/.test(fy))return json({error:'Select financial year'},400); name=`Annual-Report-${fy}.pdf`; folder='annual-reports'; } else { if(!title)return json({error:'Title required'},400); name=safeName(title)+'.pdf'; folder=type; }
 const path=`${folder}/${name}`; const bytes=new Uint8Array(await file.arrayBuffer()); let binary=''; const chunk=0x8000; for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk)); const content=btoa(binary); const existing=await gh(path,env); let sha; if(existing.ok){const x=await existing.json(); sha=x.sha;} const body={message:`CMS: publish ${path}`,content,...(sha?{sha}:{})}; const wr=await gh(path,env,'PUT',body); if(!wr.ok)return json({error:'GitHub upload failed',detail:await wr.text()},502); return json({ok:true,path}); }
 if(req.method==='GET'&&u.pathname==='/api/status')return json({ok:true}); return env.ASSETS.fetch(req); },};
